### ISSUE TITLE
Vezir login not working

### ISSUE THREAD

**Issue by marksee** [oguzhantopgul/Vezir-Project#3]
Tried vezir/vezir for username/password on the 2.0 VM and it failed. Guest login works fine though. Made sure I was typing on English keyboard as well.

Any idea if it's anything else?

**Comment by oguzhantopgul** [comment]
The login screen uses Turkish keyboard by default I assume. Sorry my fault. :(
If you are using English-US layout could you please try **vez'r** as password. If you can log in please change the layout from Keyboard Settings to English.

I'm going to update the default keyboard settings to English in the next commit.

Thanks for the feedback

**Comment by marksee** [comment]
That worked, thanks!
